parameters:
#    sinoeujobs_jobboard.example.class: Sinoeujobs\JobboardBundle\Example

services:
#    sinoeujobs_jobboard.example:
#        class: %sinoeujobs_jobboard.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
