SinoeujobsJobinBundle_job:
    resource: "@SinoeujobsJobinBundle/Resources/config/routing/job.yml"
    prefix:   /job

jobin_homepage:
    pattern:  /
    defaults: { _controller: SinoeujobsJobinBundle:Job:index }