Sinoeujobs\JobinBundle\Entity\Company:
    type: entity
    table: company
    repositoryClass: Sinoeujobs\JobinBundle\Entity\companyRepository
    id:
        id:
            type: integer
            id: true
            column: company_id
            generator:
                strategy: AUTO
    fields:
        companyName:
            type: string
            length: '128'
            column: company_name
        companyWebsite:
            type: string
            length: '128'
            column: company_website
        companyLogo:
            type: string
            length: '128'
            column: company_logo
        companyIsActived:
            type: boolean
            column: company_is_actived
        companyCreatedAt:
            type: datetime
            column: company_created_at
        companyUpdatedAt:
            type: datetime
            column: company_updated_at
            nullable: true
        companyAccessUntil:
            type: date
            column: company_access_until
            nullable: true
        userId:
            type: integer
            column: user_id
        addressId:
            type: integer
            column: address_id
    manyToOne:
        user:
            targetEntity: User
            inversedBy: companies
            joinColumn:
                name: user_id
                referencedColumnName: user_id
    oneToOne:
        address:
            targetEntity: Address
            joinColumn:
                name: address_id
                referencedColumnName: address_id
    lifecycleCallbacks:
        prePersist: [ setCompanyCreatedAt ]
        preUpdate: [ setCompanyUpdatedAt ]
