Sinoeujobs\JobinBundle\Entity\Country:
    type: entity
    table: country
    repositoryClass: Sinoeujobs\JobinBundle\Entity\CountryRepository
    id:
        countryId:
            type: integer
            id: true
            column: country_id
            generator:
                strategy: AUTO
    fields:
        countryCode:
            type: string
            length: '2'
            column: country_code
            unique: true
        countryName:
            type: string
            length: '64'
            column: country_name
            unique: true
    lifecycleCallbacks: {  }
