Sinoeujobs\JobinBundle\Entity\Job:
    type: entity
    table: null
    repositoryClass: Sinoeujobs\JobinBundle\Entity\JobRepository
    id:
        jobId:
            type: integer
            id: true
            column: job_id
            generator:
                strategy: AUTO
    fields:
        jobTitle:
            type: string
            length: '128'
            column: job_title
        jobSlug:
            type: string
            length: '128'
            column: job_slug
            unique: true
        jobCompanyName:
            type: string
            length: '128'
            column: job_company_name
        jobCompanyLogo:
            type: string
            length: '128'
            column: job_company_logo
        jobCompanyWebsite:
            type: string
            length: '128'
            column: job_company_website
        jobDescription:
            type: text
            column: job_description
        jobApply:
            type: string
            length: '255'
            column: job_apply
        jobCreatedAt:
            type: datetime
            column: job_created_at
        jobUpdatedAt:
            type: datetime
            column: job_updated_at
            nullable: true
        jobExpiresAt:
            type: date
            column: job_expires_at
            nullable: true
        jobIsApproved:
            type: boolean
            column: job_is_approved
        jobIsActive:
            type: boolean
            column: job_is_active
        jobIsFilled:
            type: boolean
            column: job_is_filled
        jobTypeId:
            type: integer
            column: job_type_id
        jobCategoryId:
            type: integer
            column: job_category_id
        ownerId:
            type: integer
            column: owner_id
        addressId:
            type: integer
            column: address_id
    manyToOne:
        jobCategory:
            targetEntity: JobCategory
            inversedBy: jobs
            joinColumn:
                name: jobCategoryId
                referencedColumnName: jobCategoryId
        jobType:
            targetEntity: JobType
            inversedBy: jobs
            joinColumn:
                name: jobTypeId
                referencedColumnName: jobTypeId
    oneToOne:
        address:
            targetEntity: Address
            joinColumn:
                name: addressId
                referencedColumnName: addressId
    lifecycleCallbacks:
        prePersist: [ setJobCreatedAt ]
        preUpdate: [ setJobUpdatedAt ]