Sinoeujobs\JobinBundle\Entity\JobCategory:
    type: entity
    table: job_category
    repositoryClass: Sinoeujobs\JobinBundle\Entity\JobCategoryRepository
    id:
        jobCategoryId:
            type: integer
            id: true
            column: job_category_id
            generator:
                strategy: AUTO
    fields:
        jobCategoryLabel:
            type: string
            length: '64'
            column: job_category_label
            unique: true
    oneToMany:
        jobs:
            targetEntity: Job
            mappedBy: jobCategory
    lifecycleCallbacks: {  }
