Sinoeujobs\JobinBundle\Entity\JobType:
    type: entity
    table: job_type
    repositoryClass: Sinoeujobs\JobinBundle\Entity\JobTypeRepository
    id:
        id:
            type: integer
            id: true
            column: job_type_id
            generator:
                strategy: AUTO
    fields:
        jobTypeLabel:
            type: string
            length: '45'
            column: job_type_label
            unique: true
    oneToMany:
        jobs:
            targetEntity: Job
            mappedBy: jobType
    lifecycleCallbacks: {  }
