Sinoeujobs\JobinBundle\Entity\JobType:
    type: entity
    table: null
    repositoryClass: Sinoeujobs\JobinBundle\Entity\JobTypeRepository
    id:
        jobTypeId:
            type: integer
            id: true
            column: job_type_id
            generator:
                strategy: AUTO
    fields:
        jobTypeLabel:
            type: string
            length: '45'
            column: job_type_label
            unique: true
    lifecycleCallbacks: {  }
