Sinoeujobs\JobinBundle\Entity\User:
    type: entity
    table: user
    repositoryClass: Sinoeujobs\JobinBundle\Entity\userRepository
    id:
        id:
            type: integer
            id: true
            column: user_id
            generator:
                strategy: AUTO
    fields:
        userLogin:
            type: string
            length: '128'
            column: user_login
            unique: true
        userPass:
            type: string
            length: '64'
            column: user_pass
        userEmail:
            type: string
            length: '128'
            column: user_email
            unique: true
        userFirstName:
            type: string
            length: '64'
            column: user_first_name
        userLastName:
            type: string
            length: '64'
            column: user_last_name
        userRegistered:
            type: datetime
            column: user_registered
        userActivationKey:
            type: string
            length: '64'
            column: user_activation_key
            unique: true
        userStatus:
            type: smallint
            column: user_status
    oneToMany:
        jobs:
            targetEntity: Job
            mappedBy: owner_id
    lifecycleCallbacks:
        prePersist: [ setUserRegistered ]
