Sinoeujobs\JobinBundle\Entity\user:
    type: entity
    table: null
    repositoryClass: Sinoeujobs\JobinBundle\Entity\userRepository
    id:
        user_id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        userLogin:
            type: string
            length: '128'
            column: user_login
        userPass:
            type: string
            length: '64'
            column: user_pass
        userEmail:
            type: string
            length: '128'
            column: user_email
        userRegistered:
            type: datetime
            column: user_registered
        userActivationKey:
            type: string
            length: '64'
            column: user_activation_key
        userStatus:
            type: smallint
            column: user_status
    lifecycleCallbacks: {  }
